# Generated by Django 4.2.1 on 2023-05-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
        ('api', '0002_kanbanboard_kanbanstage_alter_project_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanstage',
            name='board',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban.kanbanstage'),
        ),
        migrations.DeleteModel(
            name='KanbanBoard',
        ),
        migrations.DeleteModel(
            name='KanbanStage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
