# Generated by Django 4.2.1 on 2023-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_kanbanstage_taskids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanstage',
            name='taskIds',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
