# Generated by Django 4.2.1 on 2023-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('custom_user', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(to='role.role'),
        ),
    ]
